<?xml version="1.0" encoding="UTF-8"?>
<!-- 20080823 bkw: is all this leading cruft really necessary? -->
<!DOCTYPE mime-info [
  <!ELEMENT mime-info (mime-type)+>
  <!ATTLIST mime-info xmlns CDATA #FIXED "http://www.freedesktop.org/standards/shared-mime-info">

  <!ELEMENT mime-type (comment|acronym|expanded-acronym|glob|magic|root-XML|alias|sub-class-of)*>
  <!ATTLIST mime-type type CDATA #REQUIRED>

  <!-- a comment describing a document with the respective MIME type. Example: "WMV video" -->
  <!ELEMENT comment (#PCDATA)>
  <!ATTLIST comment xml:lang CDATA #IMPLIED>

  <!-- a comment describing a the respective unexpanded MIME type acronym. Example: "WMV" -->
  <!ELEMENT acronym (#PCDATA)>
  <!ATTLIST acronym xml:lang CDATA #IMPLIED>

  <!-- a comment describing a the respective unexpanded MIME type acronym. Example: "Windows Media Video" -->
  <!ELEMENT expanded-acronym (#PCDATA)>
  <!ATTLIST expanded-acronym xml:lang CDATA #IMPLIED>

  <!ELEMENT glob EMPTY>
  <!ATTLIST glob pattern CDATA #REQUIRED>

  <!ELEMENT magic (match)+>
  <!ATTLIST magic priority CDATA #IMPLIED>

  <!ELEMENT match (match)*>
  <!ATTLIST match offset CDATA #REQUIRED>
  <!ATTLIST match type (string|big16|big32|little16|little32|host16|host32|byte) #REQUIRED>
  <!ATTLIST match value CDATA #REQUIRED>
  <!ATTLIST match mask CDATA #IMPLIED>

  <!ELEMENT root-XML EMPTY>
  <!ATTLIST root-XML
  	namespaceURI CDATA #REQUIRED
	localName CDATA #REQUIRED>

  <!ELEMENT alias EMPTY>
  <!ATTLIST alias
  	type CDATA #REQUIRED>

  <!ELEMENT sub-class-of EMPTY>
  <!ATTLIST sub-class-of
  	type CDATA #REQUIRED>
]>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
  <mime-type type="application/x-atari-8bit-executable">
    <comment>Atari 8-Bit Executable</comment>
    <acronym>XEX</acronym>
    <expanded-acronym>XE eXecutable</expanded-acronym>
	 <magic priority="30">
	 	<match value="0xffff" type="big16" offset="0"/>
	 </magic>
    <glob pattern="*.xex"/>
  </mime-type>
  <mime-type type="application/x-atari-8bit-saved-basic">
    <comment>Atari 8-Bit BASIC Program</comment>
    <acronym>BAS</acronym>
    <expanded-acronym>BASic</expanded-acronym>
	 <magic priority="50">
	 	<match value="0x0000" type="big16" offset="0"/>
	 </magic>
    <glob pattern="*.bas"/>
  </mime-type>
  <mime-type type="application/x-atari-8bit-cartridge-image">
    <comment>Atari 8-Bit Cartridge Image</comment>
    <acronym>CART</acronym>
    <expanded-acronym>CARTridge</expanded-acronym>
	 <magic priority="50">
	 	<match value="CART" type="string" offset="0"/>
	 </magic>
    <glob pattern="*.cart"/>
    <glob pattern="*.car"/>
  </mime-type>
  <mime-type type="application/x-atari-8bit-disk-image">
    <comment>Atari 8-Bit Disk Image</comment>
    <acronym>ATR</acronym>
    <expanded-acronym>ATaRi</expanded-acronym>
	 <magic priority="50">
	 	<match value="0x9602" type="big16" offset="0"/>
	 </magic>
    <glob pattern="*.atr"/>
  </mime-type>
  <mime-type type="application/x-atari-8bit-raw-disk-image">
    <comment>Atari 8-Bit Disk Image (Raw)</comment>
    <acronym>XFD</acronym>
    <expanded-acronym>XFormer Disk</expanded-acronym>
    <glob pattern="*.xfd"/>
  </mime-type>
  <mime-type type="application/x-atari-8bit-cassette-image">
    <comment>Atari 8-Bit Cassette Image</comment>
    <acronym>CAS</acronym>
    <expanded-acronym>CASsette</expanded-acronym>
	 <magic priority="50">
	 	<match value="FUJI" type="string" offset="0"/>
	 </magic>
    <glob pattern="*.cas"/>
  </mime-type>
  <mime-type type="application/x-atari800-saved-state">
	 <sub-class-of type="application/x-gzip"/>
    <comment>Atari800 Emulator Saved State</comment>
    <acronym>A8S</acronym>
    <expanded-acronym>Atari800 State</expanded-acronym>
    <glob pattern="*.a8s"/>
  </mime-type>
</mime-info>
