<?xml version="1.0" encoding="UTF-8"?>
<!-- 20080823 bkw: is all this leading cruft really necessary? -->
<!DOCTYPE mime-info [
  <!ELEMENT mime-info (mime-type)+>
  <!ATTLIST mime-info xmlns CDATA #FIXED "http://www.freedesktop.org/standards/shared-mime-info">

  <!ELEMENT mime-type (comment|acronym|expanded-acronym|glob|magic|root-XML|alias|sub-class-of)*>
  <!ATTLIST mime-type type CDATA #REQUIRED>

  <!-- a comment describing a document with the respective MIME type. Example: "WMV video" -->
  <!ELEMENT comment (#PCDATA)>
  <!ATTLIST comment xml:lang CDATA #IMPLIED>

  <!-- a comment describing a the respective unexpanded MIME type acronym. Example: "WMV" -->
  <!ELEMENT acronym (#PCDATA)>
  <!ATTLIST acronym xml:lang CDATA #IMPLIED>

  <!-- a comment describing a the respective unexpanded MIME type acronym. Example: "Windows Media Video" -->
  <!ELEMENT expanded-acronym (#PCDATA)>
  <!ATTLIST expanded-acronym xml:lang CDATA #IMPLIED>

  <!ELEMENT glob EMPTY>
  <!ATTLIST glob pattern CDATA #REQUIRED>

  <!ELEMENT magic (match)+>
  <!ATTLIST magic priority CDATA #IMPLIED>

  <!ELEMENT match (match)*>
  <!ATTLIST match offset CDATA #REQUIRED>
  <!ATTLIST match type (string|big16|big32|little16|little32|host16|host32|byte) #REQUIRED>
  <!ATTLIST match value CDATA #REQUIRED>
  <!ATTLIST match mask CDATA #IMPLIED>

  <!ELEMENT root-XML EMPTY>
  <!ATTLIST root-XML
  	namespaceURI CDATA #REQUIRED
	localName CDATA #REQUIRED>

  <!ELEMENT alias EMPTY>
  <!ATTLIST alias
  	type CDATA #REQUIRED>

  <!ELEMENT sub-class-of EMPTY>
  <!ATTLIST sub-class-of
  	type CDATA #REQUIRED>
]>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
  <mime-type type="application/x-sega-master-system-rom">
    <comment>Sega Master System ROM</comment>
    <acronym>SMS</acronym>
    <expanded-acronym>Sega Master System</expanded-acronym>
    <glob pattern="*.sms"/>
  </mime-type>
  <mime-type type="application/x-sega-game-gear-rom">
    <comment>Sega Game Gear ROM</comment>
    <acronym>GG</acronym>
    <expanded-acronym>Game Gear</expanded-acronym>
    <glob pattern="*.gg"/>
  </mime-type>
</mime-info>
